### ISSUE TITLE
Questions about the SDK

### ISSUE THREAD

**Issue by elie222** [kinecosystem/kin-ecosystem-android-sdk#126]
Hi,

We were wondering what exactly is included in the SDK. Does it provide UI components for things like user balance and transactions?

We're looking to use this package in a React Native app and are wondering how much work it would be for us to rewrite it in Javascript. Can all actions be accomplished via API calls to the server? What does this package add beyond that?

**Comment by nitzantomer** [comment]
Yes, the sdk offers UI for balance, transaction history, and a marketplace.
It also offers functionality for sending kin to other addresses.
The sdk is **not** just a wrapper around http calls to our servers, the sdk also manages the wallet and communicates with the blockchain.

While it might be possible to rewrite it in js, I'd strongly recommend against it.  We are also working on a js sdk (https://github.com/kinecosystem/kin.js) but it's not ready yet.
It will probably be much easier to wrap it as a react native module, something that is also in our roadmap, but it's not clear when we'll get to it.
You're welcome to try to create the react native module for it yourself, that way you won't need to worry about implementing the sdk, but will only need to wrap it.
If you decide to go down this road, feel free to ask questions, either here or in stackoverflow using our [kin tag](https://stackoverflow.com/questions/tagged/kin).
