### ISSUE TITLE
kin sdk conflicts with com.android.support:gridlayout-v7

### ISSUE THREAD

**Issue by steelbytes** [kinecosystem/kin-ecosystem-android-sdk#151]
simply adding
   implementation ('com.github.kinfoundation.kin-ecosystem-android-sdk:sdk:0.1.+')
causes the following when compiling my app
  AAPT: error: duplicate value for resource 'attr/orientation' with config
  AAPT: error: resource previously defined here.
(with a reference to a gradle cache file containing the definition of KinEcosystemDashView

:-(

update: it's a conflict with 
  implementation ("com.android.support:gridlayout-v7:27.1.1")

**Comment by OrenZak** [comment]
@steelbytes Thanks for letting us know, we will make a fix in our next release
